name: Check Belx Flyer

on:
  schedule:
    # 毎週土曜日 10:00（日本時間）
    - cron: "0 1 * * 6"
    # 毎週土曜日 12:00（日本時間）
    - cron: "0 3 * * 6"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}

        run: |
          python app.py

      - name: Save latest flyer
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add last_flyer.txt

          git commit -m "Update last flyer" || exit 0

          git push
